### ISSUE TITLE
Test

### ISSUE THREAD

**Issue by cordageio** [cordage-io/prototype#4]
*Issue Title:* High level summary for the JTBD. Optimize the title for team understanding.

**Issue Description:**
  - **When / Situation**: What happens in the users context that makes the user want to do an action.
  - **User Motivation**: What the users want to solve for in order to maximize a gain or reduce a pain.
  - **So that:** What does the user expect to be able to do.
  - **Expected Outcome:** What would the user consider a successful outcome.

**Tasks:** Details on activities related to the task. E.G. Design Screen.
- [x] Finish my changes
- [ ] Push my commits to GitHub
- [ ] Open a pull request
  
**AC:** Acceptance Criteria
- [ ] Finish my changes
- [ ] Push my commits to GitHub
- [ ] Open a pull request
